apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-processing-deployment
spec:
  replicas: 2  # This will run 2 replicas of your container
  selector:
    matchLabels:
      app: text-processing
  template:
    metadata:
      labels:
        app: text-processing
    spec:
      containers:
      - name: text-processing-container
        image: text-processing-app:latest  # Your image name
        volumeMounts:
        - name: data-volume
          mountPath: /home/data
        command: ["python", "/home/scripts.py"]
      volumes:
      - name: data-volume
        hostPath:
          path: "/home/data"  # Adjust to the directory where your text files are located
